name: Badge Request
description: Request a CogniPilot credential badge
title: "[Badge Request] "
labels: ["badge-request"]
body:
  - type: markdown
    attributes:
      value: |
        ## Badge Request Form
        Fill out this form to request a CogniPilot credential badge.
        A maintainer will review and approve your request.

  - type: input
    id: recipient_name
    attributes:
      label: Recipient Name
      description: Full name of the badge recipient
      placeholder: "e.g., Jane Doe"
    validations:
      required: true

  - type: input
    id: recipient_email
    attributes:
      label: Recipient Email
      description: Email address for the badge recipient
      placeholder: "e.g., jane.doe@example.com"
    validations:
      required: true

  - type: dropdown
    id: achievement
    attributes:
      label: Badge Type
      description: Select the type of badge to issue
      options:
        - "CogniPilot Board of Directors 2026 (board-of-directors-2026)"
        - "CogniPilot Board of Directors 2027 (board-of-directors-2027)"
        - "CogniPilot Board of Directors 2028 (board-of-directors-2028)"
        - "CogniPilot Bronze Member 2026 (bronze-member-2026)"
        - "CogniPilot Bronze Member 2027 (bronze-member-2027)"
        - "CogniPilot Bronze Member 2028 (bronze-member-2028)"
        - "CogniPilot Collaborator (collaborator-cognipilot)"
        - "CogniPilot Contributor (contributor-cognipilot)"
        - "CogniPilot Gold Member 2026 (gold-member-2026)"
        - "CogniPilot Gold Member 2027 (gold-member-2027)"
        - "CogniPilot Gold Member 2028 (gold-member-2028)"
        - "CogniPilot Maintainer (maintainer-cognipilot)"
        - "Rumoca Maintainer (maintainer-rumoca)"
        - "CogniPilot Silver Member 2026 (silver-member-2026)"
        - "CogniPilot Silver Member 2027 (silver-member-2027)"
        - "CogniPilot Silver Member 2028 (silver-member-2028)"
        - "CogniPilot TSC Member 2026 (tsc-member-2026)"
        - "CogniPilot TSC Member 2027 (tsc-member-2027)"
        - "CogniPilot TSC Member 2028 (tsc-member-2028)"
    validations:
      required: true

  - type: input
    id: valid_from
    attributes:
      label: Valid From Date (Optional)
      description: Start date for the credential (ISO format). Leave blank for today.
      placeholder: "e.g., 2025-01-01"
    validations:
      required: false

  - type: textarea
    id: justification
    attributes:
      label: Justification
      description: Brief explanation of why this badge should be issued
      placeholder: "Describe the recipient's contributions or role..."
    validations:
      required: true
