name: Remove Credential
description: Request removal of credentials or your entire profile
title: "Removal Request"
labels: ["removal-request"]
body:
  - type: markdown
    attributes:
      value: |
        ## Credential Removal Request
        Use this form to request removal of specific credentials or your entire profile/wallet.

        **Note:** Removal is permanent. Credentials will be deleted and cannot be recovered.
        You may request new credentials in the future if needed.

        A maintainer will review and process your request.

  - type: input
    id: email
    attributes:
      label: Email Address
      description: The email address associated with the credentials you want removed
      placeholder: "e.g., your.email@example.com"
    validations:
      required: true

  - type: dropdown
    id: removal_type
    attributes:
      label: What do you want to remove?
      description: Choose whether to remove specific credentials or your entire profile
      options:
        - "Specific credentials only"
        - "Entire profile (all credentials and wallet)"
    validations:
      required: true

  - type: textarea
    id: credentials_to_remove
    attributes:
      label: Credentials to Remove (if removing specific credentials)
      description: List the credential/achievement IDs or names you want removed. Leave blank if removing entire profile.
      placeholder: |
        e.g.,
        - maintainer-cognipilot
        - tsc-member-2026
    validations:
      required: false

  - type: textarea
    id: reason
    attributes:
      label: Reason for Removal
      description: Brief explanation for this removal request
      placeholder: "e.g., Left organization, credential issued in error, privacy concerns..."
    validations:
      required: true

  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      description: Please confirm you understand the implications
      options:
        - label: I understand that this removal is permanent and cannot be undone
          required: true
        - label: I confirm that I am the owner of the email address above or authorized to request removal on their behalf
          required: true
