name: Revoke Credential
description: Request revocation of a previously issued credential
title: "Revocation Request"
labels: ["revocation-request"]
body:
  - type: markdown
    attributes:
      value: |
        ## Credential Revocation Request
        Use this form to request revocation of a credential. Revoked credentials will fail verification.

        **Important:** Revocation is typically permanent. Only request this if:
        - The credential was issued in error
        - The recipient's status has changed (e.g., no longer a contributor)
        - The credential was compromised

        A maintainer will review and approve revocation requests.

  - type: input
    id: email
    attributes:
      label: Credential Holder Email
      description: The email address associated with the credential
      placeholder: "e.g., user@example.com"
    validations:
      required: true

  - type: input
    id: achievement
    attributes:
      label: Achievement ID
      description: The achievement ID of the credential to revoke
      placeholder: "e.g., contributor-cognipilot, maintainer-rumoca"
    validations:
      required: true

  - type: dropdown
    id: reason
    attributes:
      label: Reason for Revocation
      description: Why should this credential be revoked?
      options:
        - Issued in error
        - Recipient status changed
        - Credential compromised
        - Recipient request
        - Other (explain below)
    validations:
      required: true

  - type: textarea
    id: explanation
    attributes:
      label: Additional Details
      description: Provide any additional context for this revocation request
      placeholder: "Explain why this credential should be revoked..."
    validations:
      required: true

  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      description: Please confirm you understand the implications
      options:
        - label: I understand that revocation is permanent and the credential will fail verification
          required: true
