name: Reinstate Credential
description: Request reinstatement of a previously revoked credential
title: "Reinstatement Request"
labels: ["reinstatement-request"]
body:
  - type: markdown
    attributes:
      value: |
        ## Credential Reinstatement Request
        Use this form to request reinstatement of a previously revoked credential.

        **Note:** Only credentials that were revoked can be reinstated. A maintainer will review and approve reinstatement requests.

  - type: input
    id: email
    attributes:
      label: Credential Holder Email
      description: The email address associated with the credential
      placeholder: "e.g., user@example.com"
    validations:
      required: true

  - type: input
    id: achievement
    attributes:
      label: Achievement ID
      description: The achievement ID of the credential to reinstate
      placeholder: "e.g., contributor-cognipilot, maintainer-rumoca"
    validations:
      required: true

  - type: dropdown
    id: reason
    attributes:
      label: Reason for Reinstatement
      description: Why should this credential be reinstated?
      options:
        - Revoked in error
        - Status restored
        - Issue resolved
        - Other (explain below)
    validations:
      required: true

  - type: textarea
    id: explanation
    attributes:
      label: Additional Details
      description: Provide any additional context for this reinstatement request
      placeholder: "Explain why this credential should be reinstated..."
    validations:
      required: true

  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      description: Please confirm the reinstatement
      options:
        - label: I confirm this credential should be reinstated and pass verification again
          required: true
