name: Update Credential
description: Update your credential email or profile slug
title: "Update Request"
labels: ["update-request"]
body:
  - type: markdown
    attributes:
      value: |
        ## Update Credential Details
        Use this form to update your email address or profile URL slug.

        **Note:** If you have credentials in multiple wallets (e.g., from using different email addresses),
        updating to an email that already has a wallet will consolidate/merge your credentials into that existing wallet.

        A maintainer will review and approve your request.

  - type: input
    id: current_email
    attributes:
      label: Current Email
      description: The email address currently associated with your credentials
      placeholder: "e.g., old.email@example.com"
    validations:
      required: true

  - type: input
    id: new_email
    attributes:
      label: New Email (Optional)
      description: Leave blank if you only want to change your profile slug
      placeholder: "e.g., new.email@example.com"
    validations:
      required: false

  - type: input
    id: new_slug
    attributes:
      label: New Profile Slug (Optional)
      description: The URL-friendly name for your profile (lowercase, hyphens only). Leave blank to keep current.
      placeholder: "e.g., jane-doe"
    validations:
      required: false

  - type: checkboxes
    id: anonymize_slug
    attributes:
      label: Anonymous Wallet
      description: Replace your current wallet URL with a random alphanumeric identifier
      options:
        - label: Convert to anonymous wallet slug (overrides New Profile Slug above)
          required: false

  - type: textarea
    id: reason
    attributes:
      label: Reason for Update
      description: Brief explanation for this update request
      placeholder: "e.g., Changed organization email, name correction, consolidate credentials from multiple wallets..."
    validations:
      required: true
